// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HotelariaControle.Data.Models
{
    public partial class Consumo
    {
        [Key]
        [Column("Id_Consumo")]
        public int IdConsumo { get; set; }
        public int Quantidade { get; set; }
        public double Preco { get; set; }
        [Column("Data_Venda", TypeName = "date")]
        public DateTime DataVenda { get; set; }
        [Column("Id_Reserva")]
        public int? IdReserva { get; set; }
        [Column("Id_Produto")]
        public int? IdProduto { get; set; }

        [ForeignKey(nameof(IdProduto))]
        [InverseProperty(nameof(Produtos.Consumo))]
        public virtual Produtos IdProdutoNavigation { get; set; }
        [ForeignKey(nameof(IdReserva))]
        [InverseProperty(nameof(Reservas.Consumo))]
        public virtual Reservas IdReservaNavigation { get; set; }
    }
}