// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HotelariaControle.Data.Models
{
    public partial class Fornecedores
    {
        [Key]
        [Column("Id_Fornecedor")]
        public int IdFornecedor { get; set; }
        [Column("Id_Produto")]
        public int? IdProduto { get; set; }
        [Required]
        [Column("Nome_Fornecedor")]
        [StringLength(50)]
        public string NomeFornecedor { get; set; }
        [Required]
        [StringLength(14)]
        public string Telefone { get; set; }
        [Column("Telefone_Alt")]
        [StringLength(14)]
        public string TelefoneAlt { get; set; }
        [Column("Fc_Status")]
        public bool FcStatus { get; set; }

        [ForeignKey(nameof(IdProduto))]
        [InverseProperty(nameof(Produtos.Fornecedores))]
        public virtual Produtos IdProdutoNavigation { get; set; }
    }
}