// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HotelariaControle.Data.Models
{
    [Index(nameof(Cpf), Name = "UQ__Hospedes__C1F897312709E163", IsUnique = true)]
    public partial class Hospedes
    {
        public Hospedes()
        {
            Reservas = new HashSet<Reservas>();
            Usuarios = new HashSet<Usuarios>();
        }

        [Key]
        [Column("Id_Hospede")]
        public int IdHospede { get; set; }
        [Required]
        [StringLength(50)]
        public string Nome { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(11)]
        public string Cpf { get; set; }
        [Column("Data_de_Nascimento", TypeName = "date")]
        public DateTime DataDeNascimento { get; set; }
        [Required]
        [StringLength(14)]
        public string Telefone { get; set; }
        [Column("Telefone_Alt")]
        [StringLength(14)]
        public string TelefoneAlt { get; set; }
        [Column("H_Status")]
        public bool HStatus { get; set; }

        [InverseProperty("IdHospedeNavigation")]
        public virtual ICollection<Reservas> Reservas { get; set; }
        [InverseProperty("IdHospedeNavigation")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}