// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HotelariaControle.Data.Models
{
    public partial class Produtos
    {
        public Produtos()
        {
            Consumo = new HashSet<Consumo>();
            Fornecedores = new HashSet<Fornecedores>();
        }

        [Key]
        [Column("Id_Produto")]
        public int IdProduto { get; set; }
        [Required]
        [Column("Nome_Produto")]
        [StringLength(50)]
        public string NomeProduto { get; set; }
        [Column("Valor_Compra")]
        public double ValorCompra { get; set; }
        [Column("Valor_Venda")]
        public double ValorVenda { get; set; }
        [Column("Estoque_Inicial")]
        public int EstoqueInicial { get; set; }
        public int Quantidade { get; set; }

        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<Consumo> Consumo { get; set; }
        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<Fornecedores> Fornecedores { get; set; }
    }
}