// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HotelariaControle.Data.Models
{
    public partial class Reservas
    {
        public Reservas()
        {
            Consumo = new HashSet<Consumo>();
        }

        [Key]
        [Column("Id_Reserva")]
        public int IdReserva { get; set; }
        [Column(TypeName = "date")]
        public DateTime CheckIn { get; set; }
        [Column(TypeName = "date")]
        public DateTime CheckOut { get; set; }
        [Column("Id_Quarto")]
        public int? IdQuarto { get; set; }
        [Column("Id_Hospede")]
        public int? IdHospede { get; set; }
        [Column("R_Status")]
        public bool RStatus { get; set; }

        [ForeignKey(nameof(IdHospede))]
        [InverseProperty(nameof(Hospedes.Reservas))]
        public virtual Hospedes IdHospedeNavigation { get; set; }
        [ForeignKey(nameof(IdQuarto))]
        [InverseProperty(nameof(Quartos.Reservas))]
        public virtual Quartos IdQuartoNavigation { get; set; }
        [InverseProperty("IdReservaNavigation")]
        public virtual ICollection<Consumo> Consumo { get; set; }
    }
}