CREATE DATABASE BD_Hotel
GO
USE BD_Hotel
GO
IF OBJECT_ID(N'Reservas') IS NOT NULL
DROP TABLE Reservas
Go
CREATE TABLE Reservas(
Id_Reserva INT IDENTITY,
CheckIn DATE NOT NULL,
CheckOut DATE NOT NULL,
Id_Quarto INT,
Id_Hospede INT,
R_Status BIT NOT NULL,
CONSTRAINT PK_RESERVA PRIMARY KEY(Id_Reserva))
GO
IF OBJECT_ID(N'Consumo') IS NOT NULL
DROP TABLE Consumo
GO
CREATE TABLE Consumo (
Id_Consumo INT IDENTITY,
Quantidade INT NOT NULL,
Preco FLOAT NOT NULL,
Data_Venda DATE NOT NULL,
Id_Reserva INT,
Id_Produto INT,
CONSTRAINT PK_CONSUMO PRIMARY KEY(Id_Consumo))
GO
IF OBJECT_ID (N'Produtos') IS NOT NULL
DROP TABLE Produtos
GO
CREATE TABLE Produtos (
Id_Produto INT IDENTITY,
Nome_Produto VARCHAR(50) NOT NULL,
Valor_Compra FLOAT NOT NULL,
Valor_Venda FLOAT NOT NULL,
Estoque_Inicial INT NOT NULL,
Quantidade INT NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY(Id_Produto))
GO
IF OBJECT_ID(N'Fornecedores') IS NOT NULL
DROP TABLE Fornecedores
GO
CREATE TABLE Fornecedores (
Id_Fornecedor INT IDENTITY,
Id_Produto INT,
Nome_Fornecedor VARCHAR(50) NOT NULL,
Telefone CHAR(14) NOT NULL,
Telefone_Alt CHAR(14),
Fc_Status BIT NOT NULL,
CONSTRAINT PK_FORNECEDOR PRIMARY KEY(Id_Fornecedor))
GO
IF OBJECT_ID(N'Hospedes') IS NOT NULL
DROP TABLE Hospedes
GO
CREATE TABLE Hospedes (
Id_Hospede INT IDENTITY,
Nome VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
Data_de_Nascimento DATE NOT NULL,
Telefone CHAR(14) NOT NULL,
Telefone_Alt CHAR(14),
H_Status BIT NOT NULL,
CONSTRAINT PK_HOSPEDE PRIMARY KEY(Id_Hospede))
GO
IF OBJECT_ID(N'Funcionarios') IS NOT NULL
DROP TABLE Funcionarios
GO
CREATE TABLE Funcionarios (
Id_Funcionario INT IDENTITY,
Nome VARCHAR(50) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
RG VARCHAR(15) NOT NULL,
Email VARCHAR(50) NOT NULL,
Cargo VARCHAR(30) NOT NULL,
Telefone CHAR(14) NOT NULL,
Telefone_Alt CHAR(14),
Salario FLOAT NOT NULL,
Data_de_Admissão DATE NOT NULL,
F_Status BIT NOT NULL,
CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(Id_Funcionario))
GO
IF OBJECT_ID (N'Usuarios') IS NOT NULL
DROP TABLE Usuarios
GO
CREATE TABLE Usuarios (
Id_Usuario INT IDENTITY,
Usuario VARCHAR(20) UNIQUE NOT NULL,
Senha VARCHAR(20) NOT NULL,
Tipo VARCHAR(20) NOT NULL,
Id_Hospede INT,
Id_Funcionario INT,
U_Status BIT NOT NULL,
CONSTRAINT PK_USUARIO PRIMARY KEY(Id_Usuario))
GO
IF OBJECT_ID (N'Quartos') IS NOT NULL
DROP TABLE Quartos
GO
CREATE TABLE Quartos (
Id_Quarto INT IDENTITY,
Numero_Quarto INT NOT NULL,
Tipo_Quarto VARCHAR(20) NOT NULL,
CONSTRAINT PK_QUARTO PRIMARY KEY(Id_Quarto))
GO


ALTER TABLE Reservas ADD CONSTRAINT FK_IdQuarto
FOREIGN KEY(Id_Quarto)
REFERENCES Quartos(Id_Quarto)
GO
ALTER TABLE Reservas ADD CONSTRAINT FK_IdHospede
FOREIGN KEY(Id_Hospede)
REFERENCES Hospedes(Id_Hospede)
GO
ALTER TABLE Usuarios ADD CONSTRAINT FK_IdFuncionario
FOREIGN KEY(Id_Funcionario)
REFERENCES Funcionarios(Id_Funcionario)
GO
ALTER TABLE Usuarios ADD CONSTRAINT FK__IdHospede
FOREIGN KEY(Id_Hospede)
REFERENCES Hospedes(Id_Hospede)
GO
ALTER TABLE Consumo ADD CONSTRAINT FK_IdReserva
FOREIGN KEY(Id_Reserva)
REFERENCES Reservas(Id_Reserva)
GO
ALTER TABLE Consumo ADD CONSTRAINT FK_Produto
FOREIGN KEY(Id_Produto)
REFERENCES Produtos(Id_Produto)
GO
ALTER TABLE Fornecedores ADD CONSTRAINT FK__Produto
FOREIGN KEY(Id_Produto)
REFERENCES Produtos(Id_Produto)
GO

SELECT *FROM Consumo
SELECT *FROM Fornecedores
SELECT *FROM Funcionarios
SELECT *FROM Hospedes 
SELECT *FROM Produtos
SELECT *FROM Quartos 
SELECT *FROM Reservas
SELECT *FROM Usuarios
